name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: cd release && zip -r ../MonsterTrainAccessibility-${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: MonsterTrainAccessibility-${{ github.ref_name }}.zip
          generate_release_notes: true
